### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by matk0** [rwjblue/ember-cli-pretender#30]
While following: http://reefpoints.dockyard.com/2014/05/09/building-an-ember-app-with-rails-part-3.html, I install `ember install:addon ember-cli-pretender`. When I try to run the server after that, I get: 
```
Livereload server on port 35729
Serving on http://localhost:4200/
self is not defined
ReferenceError: self is not defined
    at JSHinter.getConfig (/Users/matejlukasik/Documents/unpolluteit/ember/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/index.js:114:7)
    at /Users/matejlukasik/Documents/unpolluteit/ember/node_modules/ember-cli-qunit/node_modules/broccoli-jshint/index.js:37:28
    at lib$rsvp$$internal$$tryCatch (/Users/matejlukasik/Documents/unpolluteit/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/matejlukasik/Documents/unpolluteit/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/matejlukasik/Documents/unpolluteit/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/matejlukasik/Documents/unpolluteit/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```
Why is that? Can anyone help?

**Comment by rwjblue** [comment]
Seems like the error is with broccoli-jshint, and was recently fixed there. It only is fired when your jshintrc is invalid, likely you added Pretender to itake with a typo.
